# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwmZAw0_aDjwiARjvhfKXxMt9Z37HIZ0
"""

x=int(input("Type the first number:"))
print()
operators=input("+,-,*,/  :")
print()
y=int(input("Type the second number: "))
print()
if operators=="+":
    print(x+y)
elif operators=="-":
    print(x-y)
elif operators=="*":
    print(x*y)
elif operators=="/":
    print(x/y)
else:
   print("Invalid Output")